version: "3"
services:
  bowling-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - mongo
    ports:
      - 9000:80
  mongo:
    build:
        context: .
        dockerfile: Dockerfile_mongo
    ports:
        - 27017
